using Content.Client.UserInterface.Controls;
using Content.Shared.Xenobiology;
using Content.Shared.Xenobiology.Systems;
using Content.Shared.Xenobiology.UI;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;
using Robust.Shared.Timing;
using Robust.Shared.Utility;

namespace Content.Client.Xenobiology.UI;

[GenerateTypedNameReferences]
public sealed partial class CellularFusionWindow : FancyWindow
{
    [Dependency] private readonly IPrototypeManager _prototype = default!;
    [Dependency] private readonly IEntityManager _entity = default!;
    [Dependency] private readonly IGameTiming _timing = default!;

    private readonly CellSystem _cell;

    public event Action<Cell, Cell>? OnSplice;

    private CellEntryControl? _selectedEntryA;
    private CellEntryControl? _selectedEntryB;

    private int _material;
    private bool _spliceInProgress;
    private TimeSpan _spliceStartTime;

    public CellularFusionWindow()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        _cell = _entity.System<CellSystem>();

        SetMaterialCount(0);

        SpliceButton.OnPressed += _ =>
        {
            if (_selectedEntryA?.Cell is not { } cellA || _selectedEntryB?.Cell is not { } cellB)
                return;

            OnSplice?.Invoke(cellA, cellB);
        };
    }

    public void UpdateState(CellularFusionUiState state)
    {
        SetMaterialCount(state.Material);

        CellContainerA.RemoveAllChildren();
        foreach (var savedCell in state.RemoteCells)
        {
            var entry = new CellEntryControl(savedCell, false);
            entry.OnSelect += SelectedCellEntryA;

            CellContainerA.AddChild(entry);
        }

        CellContainerB.RemoveAllChildren();
        foreach (var savedCell in state.RemoteCells)
        {
            var entry = new CellEntryControl(savedCell, false);
            entry.OnSelect += SelectedCellEntryB;

            CellContainerB.AddChild(entry);
        }

        if (state.SpliceInProgress && !_spliceInProgress)
        {
            _spliceInProgress = true;
            _spliceStartTime = _timing.RealTime;
        }
        else if (!state.SpliceInProgress && _spliceInProgress)
        {
            _spliceInProgress = false;
            SpliceProgressBar.Visible = false;

            if (state.LastResult is { } result)
                ShowResult(result);
            else
                ClearSelection();
        }

        SpliceProgressBar.Visible = _spliceInProgress;
        CellNameLabel.Visible = !_spliceInProgress;
        CellColorLabel.Visible = !_spliceInProgress;
        CellStabilityLabel.Visible = !_spliceInProgress;
        CellCostLabel.Visible = !_spliceInProgress;
        CellModifiersText.Visible = !_spliceInProgress;
    }

    private void ClearSelection()
    {
        _selectedEntryA = null;
        _selectedEntryB = null;
        CellANoSelectedLabel.Visible = true;
        CellBNoSelectedLabel.Visible = true;
        CellInfoContainer.Visible = false;
        SpliceButton.Disabled = true;
    }

    private void ShowResult(Cell cell)
    {
        _selectedEntryA = null;
        _selectedEntryB = null;
        CellANoSelectedLabel.Visible = false;
        CellBNoSelectedLabel.Visible = false;
        CellInfoContainer.Visible = true;
        SpliceButton.Disabled = true;

        SetCellInfoName(cell.Name);
        SetCellInfoColor(cell.Color);
        SetCellInfoStability(cell.Stability);
        SetCellInfoCost(cell.Cost);
        SetCellInfoModifiers(cell.Modifiers);
    }

    private void SelectedCellEntryA(CellEntryControl entry)
    {
        SelectCellEntry(entry, ref _selectedEntryA);
        CellANoSelectedLabel.Visible = _selectedEntryA is null;
        UpdateCellInfo();
    }

    private void SelectedCellEntryB(CellEntryControl entry)
    {
        SelectCellEntry(entry, ref _selectedEntryB);
        CellBNoSelectedLabel.Visible = _selectedEntryB is null;
        UpdateCellInfo();
    }

    private void SelectCellEntry(CellEntryControl? entryNew, ref CellEntryControl? entryPrevious)
    {
        entryPrevious?.SetState(true);
        entryNew?.SetState(false);

        entryPrevious = entryNew;
    }

    private void UpdateCellInfo()
    {
        var selected = _selectedEntryA is not null && _selectedEntryB is not null;

        CellInfoContainer.Visible = selected;
        SpliceButton.Disabled = true;

        if (_selectedEntryA is not { } entryA || _selectedEntryB is not { } entryB)
            return;

        var cost = SharedCellSystem.GetMergedCost(entryA.Cell, entryB.Cell);
        var hasMaterial = cost <= _material;

        SpliceButton.Disabled = !hasMaterial || _spliceInProgress;

        SetCellInfoName("???");
        SetCellInfoColor(Color.White);
        SetCellInfoStability(0);
        SetCellInfoCost(cost);
        SetCellInfoModifiers([]);
    }

    private void SetMaterialCount(int count)
    {
        _material = count;

        MaterialLabel.Text = Loc.GetString("cellular-fusion-menu-cell-material-label", ("material", _material));
    }

    private void SetCellInfoName(string name)
    {
        CellNameLabel.Text = Loc.GetString("cellular-fusion-menu-cell-name-label", ("name", name));
    }

    private void SetCellInfoColor(Color color)
    {
        var colorTitle = Loc.GetString("cellular-fusion-menu-cell-color-label", ("color", color.ToHex()));

        if (!FormattedMessage.TryFromMarkup(colorTitle, out var colorMarkup))
        {
            CellColorLabel.SetMessage(colorTitle);
            return;
        }

        CellColorLabel.SetMessage(colorMarkup);
    }

    private void SetCellInfoStability(float stability)
    {
        CellStabilityLabel.Text = Loc.GetString("cellular-fusion-menu-cell-stability-label", ("stability", Math.Round(stability * 100f, 3)));
    }

    private void SetCellInfoCost(int cost)
    {
        CellCostLabel.Text = Loc.GetString("cellular-fusion-menu-cell-cost-label", ("cost", cost));
    }

    private void SetCellInfoModifiers(List<ProtoId<CellModifierPrototype>> modifiers)
    {
        var message = _cell.GetCellModifiersString(modifiers);

        if (!FormattedMessage.TryFromMarkup(message, out var markup))
        {
            CellModifiersText.SetMessage(message);
            return;
        }

        CellModifiersText.SetMessage(markup);
    }

    protected override void FrameUpdate(FrameEventArgs args)
    {
        base.FrameUpdate(args);

        if (!_spliceInProgress)
            return;

        var elapsed = (_timing.RealTime - _spliceStartTime).TotalSeconds;
        var progress = Math.Clamp(elapsed / 5.0 * 100.0, 0.0, 100.0);
        SpliceProgressBar.Value = (float)progress;
    }
}
